function getInfo() {
	window.numberOfQuestions = 	10;
	window.currentSlide = 		0;
	window.currentScore = 		0;
	window.title = 				"WWE TRIVIA";
	window.questions = [		"THE LONGEST REIGNING WWE CHAMPION OF ALL TIME IS...",
								"THIS WWE HALL OF FAMER NEVER HELD THE WWE CHAMPIONSHIP.",
								"THIS SUPERSTAR IS KNOWN BY THE NICKNAME 'THE GAME'.", 
								"THIS WRESTLING SUPERSTAR IS A THIRD GENERATION WRESTLER.", 
								"THE INAUGURAL INTERCONTINENTAL CHAMPION WAS...",
								"HOW MANY PARTICIPANTS TAKE PART IN A TRADITIONAL ROYAL RUMBLE MATCH?", 
								"THIS WRESTLING TAG TEAM WAS FAMED FOR USING STEEL CHAIRS AS WEAPONS.",
								"THIS WRESTLER FINISHES HIS OPPONENTS WITH A MANUEVER KNOWN AS THE RKO.",
								"THIS WRESTLER WAS A PART OF A FACTION KNOWN AS THE SHIELD.",
								"WHO IS THE ONLY WOMAN TO HOLD THE INTERCONTINENTAL CHAMPIONSHIP?" ];
	
	window.correctAnswer = [ 	"D", "B", "C", "B", "A", "D", "E", "C", "A", "E"]; 
	
	window.answerA = [ 			"HULK HOGAN", 
								"BRET HART", 
								"RIC FLAIR", 
								"GOLDUST", 
								"PAT PATTERSON",
								"15",
								"THE DUDLEY BOYZ",
								"STEVE AUSTIN",
								"SETH ROLLINS",
								"BULL NAKANO"];
	
	window.answerB = [ 			"SUPERSTAR BILLY GRAHAM", 
								"MR. PERFECT", 
								"BATISTA", 
								"THE ROCK",
								"DOINK THE CLOWN",
								"20",
								"THE HART FOUNDATION",
								"BROCK LESNAR",
								"DANIEL BRYAN", 
								"JACQUELINE"];
	
	window.answerC = [ 			"PEDRO MORALES",
								"ANDRE THE GIANT",
								"TRIPLE H", 
								"KEVIN OWENS", 
								"IRWIN R SCHYSTER",
								"25",
								"THE NASTY BOYS",
								"RANDY ORTON",
								"SHEAMUS",
								"NIA JAX" ];
								
	window.answerD = [ 			"BRUNO SAMMARTINO",
								"THE IRON SHEIK",
								"JOHN CENA", 
								"BRAUN STROWMAN",
								"DON MURACO",
								"30",
								"DEMOLITION",
								"JOHN CENA",
								"BRAY WYATT",
								"BETH PHOENIX"];
								
	window.answerE = [ 			"IVAN PUTSKI", 
								"DIESEL", 
								"AJ STYLES", 
								"BOOKER T",
								"TITO SANTANA",
								"35",
								"EDGE AND CHRISTIAN",
								"RANDY SAVAGE",
								"THE BIG SHOW",
								"CHYNA"];
								
	window.response = [ 		"SAMMARTINO HELD THE WORLD CHAMPIONSHIP FOR OVER 4,000 DAYS ACROSS TWO REIGNS.", 
								"MR PERFECT WON THE INTERCONTINENTAL CHAMPIONSHIP MULTIPLE TIMES, BUT NEVER HELD THE WORLD TITLE.", 
								"TRIPLE H IS ONE OF THE MOST DECORATED WRESTLERS IN THE BUSINESS, AND HAS WON THE WWE CHAMPIONSHIP 9 TIMES.", 
								"THE ROCK IS THE SON OF ROCKY JOHNSON AND THE GRANDSON OF HIGH CHIEF PETER MAIVIA.", 
								"PATTERSON BECAME THE FIRST INTERCONTINENTAL CHAMPIONSHIP ON SEPTEMBER 1, 1979.",
								"THE MATCH BEGINS WITH 2 PARTICIPANTS, AND THE REMAINING 28 PARTICIPENTS ENTER AT TIMED INTERVALS.",
								"THIS DUO INNOVATED THE 'CON-CHAIR-TO' TECHNIQUE, IN WHICH BOTH MEMBERS STRIKE THEIR OPPONENT WITH A STEEL CHAIR AT THE SAME TIME.",
								"THE RKO BECAME A VIRAL MEME DUE TO THE MOVE OFTEN BEING PERFORMED 'FROM OUTTA NOWHERE'.",
								"SETH ROLLINS MADE HIS DEBUT IN 2012 ALONGSIDE ROMAN REIGNS AND DEAN AMBROSE, AND THE TRIO IMMEDIATELY ESTABLISHED THEMSELVES AS STARS.",
								"CHYNA DEFEATED JEFF JARRETT IN 1999 TO BECOME THE FIRST AND ONLY WOMAN TO HOLD THE INTERCONTINETAL CHAMPIONSHIP." ];
							
}
						